AWSTemplateFormatVersion: 2010-09-09
Description: SNS+LambdaSAM deployment stack.
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApprovalStepArn:
    Type: CommaDelimitedList
    Description: Arn for the manual approval, format(arn:aws:codepipeline:region:aws-account-id:pipeline-name/stage-name/action-name)
    Default: "*"
  ChannelId:
    Type: String
    Description: Channel ID of the slack channel
  ProjectName:
    Type: String
    Description: Project name or app name.
    Default: checkpoint
  SlackOAuthToken:
    Type: String
    Description: OAuth Token for API request to slack
    Default: checkpoint
  SlackVerificationToken:
    Type: String
    Description: Verification Token for Approval Handler Function
  SnsTopicName:
    Type: String
    Description: SNS Topic Name
    Default: Approval-Notifications-01
  TableName:
    Type: String
    Description: Table name to be created in DynamoDB
    Default: ManualApprovalTracker

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref SnsTopicName
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
      TopicName: !Ref SnsTopicName

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt SlackNotification.Arn
      Protocol: LAMBDA
      TopicArn: !Ref SNSTopic

  DynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: action_execution_id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: action_execution_id
          KeyType: HASH
      TableName: !Ref TableName

  SlackNotification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./slack-notification
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          CHANNEL_ID: !Ref ChannelId
          SLACK_OAUTH_TOKEN: !Ref SlackOAuthToken
          TABLE_NAME: !Ref TableName
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:eu-west-1:961354904951:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:eu-west-1:961354904951:log-group:/aws/lambda/SlackNotificationFunction:*
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt DynamoTable.Arn
      SnapStart:
        ApplyOn: None
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic

  ApprovalHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./approval-handler
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          SLACK_VERIFICATION_TOKEN: !Ref SlackVerificationToken
          TABLE_NAME: !Ref TableName
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - codepipeline:PutApprovalResult
              Resource: !Ref ApprovalStepArn
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:UpdateItem
              Resource:
                - !GetAtt DynamoTable.Arn
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /ApprovalHandlerTest
            Method: POST

  ApprovalResultHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./approval-result-handler
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          CHANNEL_ID: !Ref ChannelId
          SLACK_OAUTH_TOKEN: !Ref SlackOAuthToken
          TABLE_NAME: !Ref TableName
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:DeleteItem
                - dynamodb:Scan
                - dynamodb:GetItem
              Resource:
                - !GetAtt DynamoTable.Arn
      SnapStart:
        ApplyOn: None
      Events:
        CloudwatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source:
                - aws.codepipeline
              detail-type:
                - CodePipeline Action Execution State Change
              detail:
                state:
                  - SUCCEEDED
                  - FAILED
                type:
                  category:
                    - Approval
