AWSTemplateFormatVersion: 2010-09-09
Description: SNS+LambdaSAM deployment stack.
Transform: AWS::Serverless-2016-10-31

Parameters:
  ApprovalStepArn:
    Type: CommaDelimitedList
    Description: Arn for the manual approval, format(arn:aws:codepipeline:region:aws-account-id:pipeline-name/stage-name/action-name)
  ProjectName:
    Type: String
    Description: Project name or app name.
    Default: checkpoint
  SlackVerificationToken:
    Type: String
    Description: Verification Token for Approval Handler Function
  SlackWebhookUrl:
    Type: String
    Description: Slack Webhook URL for Approval Notification Function
  SnsTopicName:
    Type: String
    Description: SNS Topic Name
    Default: Approval-Notifications

Resources:
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Ref SnsTopicName
      Tags:
        - Key: ProjectName
          Value: !Ref ProjectName
      TopicName: !Ref SnsTopicName

  SNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: !GetAtt SlackNotification.Arn
      Protocol: LAMBDA
      TopicArn: !Ref SNSTopic

  SlackNotification:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./slack-notification
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          SLACK_WEBHOOK_URL: !Ref SlackWebhookUrl
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: arn:aws:logs:eu-west-1:961354904951:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - >-
                  arn:aws:logs:eu-west-1:961354904951:log-group:/aws/lambda/SlackNotificationFunction:*
      SnapStart:
        ApplyOn: None
      Events:
        SNS1:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic

  ApprovalHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./approval-handler
      MemorySize: 128
      Timeout: 3
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          SLACK_VERIFICATION_TOKEN: !Ref SlackVerificationToken
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - codepipeline:PutApprovalResult
              Resource: !Ref ApprovalStepArn
      SnapStart:
        ApplyOn: None
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /ApprovalHandler
            Method: POST
